export const topSearchesList = [
    {
        id: '1',
        userProfilePic: require('../../assets/images/users/user3.png'),
        userProfileName: 'dennyjohn._',
        userFullName: 'Denny John',
        isFollow: true,
        storyAvailable: true,
    },
    {
        id: '2',
        userProfilePic: require('../../assets/images/users/user2.png'),
        userProfileName: 'alicia___',
        userFullName: 'Alicia Sierra',
        isFollow: true,
        storyAvailable: true,
    },
    {
        id: '3',
        userProfilePic: require('../../assets/images/users/user15.png'),
        userProfileName: 'tishaaaa',
        userFullName: 'Tisha Jain',
        isFollow: false,
        storyAvailable: false,
    },
    {
        id: '4',
        userProfilePic: require('../../assets/images/users/user16.png'),
        userProfileName: 'benafsha.',
        userFullName: 'Benafsha Doe',
        isFollow: false,
        storyAvailable: true,
    },
    {
        id: '5',
        userProfilePic: require('../../assets/images/users/user17.png'),
        userProfileName: 'tonny_.',
        userFullName: 'Tonny Shah',
        isFollow: false,
        storyAvailable: false,
    },
    {
        id: '6',
        userProfilePic: require('../../assets/images/users/user18.png'),
        userProfileName: 'realimranali',
        userFullName: 'Imran Ali',
        isFollow: false,
        storyAvailable: false,
    },
    {
        id: '7',
        userProfilePic: require('../../assets/images/users/user3.png'),
        userProfileName: 'dennyjohn._',
        userFullName: 'Denny John',
        isFollow: false,
        storyAvailable: true,
    },
    {
        id: '8',
        userProfilePic: require('../../assets/images/users/user2.png'),
        userProfileName: 'alicia___',
        userFullName: 'Alicia Sierra',
        isFollow: false,
        storyAvailable: true,
    },
    {
        id: '9',
        userProfilePic: require('../../assets/images/users/user15.png'),
        userProfileName: 'tishaaaa',
        userFullName: 'Tisha Jain',
        isFollow: false,
        storyAvailable: false,
    },
    {
        id: '10',
        userProfilePic: require('../../assets/images/users/user16.png'),
        userProfileName: 'benafsha.',
        userFullName: 'Benafsha Doe',
        isFollow: false,
        storyAvailable: true,
    },
    {
        id: '11',
        userProfilePic: require('../../assets/images/users/user3.png'),
        userProfileName: 'dennyjohn._',
        userFullName: 'Denny John',
        isFollow: false,
        storyAvailable: true,
    },
    {
        id: '12',
        userProfilePic: require('../../assets/images/users/user2.png'),
        userProfileName: 'alicia___',
        userFullName: 'Alicia Sierra',
        isFollow: false,
        storyAvailable: true,
    },
    {
        id: '13',
        userProfilePic: require('../../assets/images/users/user15.png'),
        userProfileName: 'tishaaaa',
        userFullName: 'Tisha Jain',
        isFollow: false,
        storyAvailable: false,
    },
];

export const accountSearchesList = [
    {
        id: '1',
        userProfilePic: require('../../assets/images/users/user3.png'),
        userProfileName: 'dennyjohn._',
        userFullName: 'Denny John',
        isFollow: true,
        storyAvailable: true,
    },
    {
        id: '2',
        userProfilePic: require('../../assets/images/users/user2.png'),
        userProfileName: 'alicia___',
        userFullName: 'Alicia Sierra',
        isFollow: true,
        storyAvailable: true,
    },
    {
        id: '3',
        userProfilePic: require('../../assets/images/users/user15.png'),
        userProfileName: 'tishaaaa',
        userFullName: 'Tisha Jain',
        isFollow: false,
        followedByUsers: ['alicia___', '', '', '', '', '', '', ''],
        storyAvailable: false,
    },
    {
        id: '4',
        userProfilePic: require('../../assets/images/users/user16.png'),
        userProfileName: 'benafsha.',
        userFullName: 'Benafsha Doe',
        isFollow: false,
        followedByUsers: ['smiti_', '', '', '', '', '', '', '', '', '', '', ''],
        storyAvailable: true,
    },
    {
        id: '5',
        userProfilePic: require('../../assets/images/users/user17.png'),
        userProfileName: 'tonny_.',
        userFullName: 'Tonny Shah',
        isFollow: true,
        storyAvailable: false,
    },
    {
        id: '6',
        userProfilePic: require('../../assets/images/users/user18.png'),
        userProfileName: 'realimranali',
        userFullName: 'Imran Ali',
        isFollow: false,
        followedByUsers: ['alicia___', '', '', '', '', '', ''],
        storyAvailable: false,
    },
    {
        id: '7',
        userProfilePic: require('../../assets/images/users/user3.png'),
        userProfileName: 'dennyjohn._',
        userFullName: 'Denny John',
        isFollow: true,
        storyAvailable: true,
    },
    {
        id: '8',
        userProfilePic: require('../../assets/images/users/user2.png'),
        userProfileName: 'alicia___',
        userFullName: 'Alicia Sierra',
        isFollow: false,
        followedByUsers: ['smiti_', '', '', '', '', '', '', '', '', '', ''],
        storyAvailable: true,
    },
    {
        id: '9',
        userProfilePic: require('../../assets/images/users/user15.png'),
        userProfileName: 'tishaaaa',
        userFullName: 'Tisha Jain',
        isFollow: false,
        followedByUsers: ['alicia___', '', '', '', '', '', '', '', ''],
        storyAvailable: false,
    },
    {
        id: '10',
        userProfilePic: require('../../assets/images/users/user16.png'),
        userProfileName: 'benafsha.',
        userFullName: 'Benafsha Doe',
        isFollow: false,
        followedByUsers: ['smiti_', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        storyAvailable: true,
    },
    {
        id: '11',
        userProfilePic: require('../../assets/images/users/user3.png'),
        userProfileName: 'dennyjohn._',
        userFullName: 'Denny John',
        isFollow: false,
        followedByUsers: ['alicia___', '', '', '', '', '', ''],
        storyAvailable: true,
    },
    {
        id: '12',
        userProfilePic: require('../../assets/images/users/user2.png'),
        userProfileName: 'alicia___',
        userFullName: 'Alicia Sierra',
        isFollow: false,
        followedByUsers: ['alicia___', '', '', '', '', '', ''],
        storyAvailable: true,
    },
    {
        id: '13',
        userProfilePic: require('../../assets/images/users/user15.png'),
        userProfileName: 'tishaaaa',
        userFullName: 'Tisha Jain',
        isFollow: true,
        storyAvailable: false,
    },
];

export const tagSearchesList = [
    {
        id: '1',
        userProfilePic: require('../../assets/images/users/user19.png'),
        hastag: '#surfing',
        postsCount: '1.5m',
    },
    {
        id: '21',
        userProfilePic: require('../../assets/images/users/user20.png'),
        hastag: '#landscape',
        postsCount: '57,793,278',
    },
    {
        id: '3',
        userProfilePic: require('../../assets/images/users/user21.png'),
        hastag: '#landscapephotography',
        postsCount: '57,793,278',
    },
    {
        id: '4',
        userProfilePic: require('../../assets/images/users/user22.png'),
        hastag: '#storyart',
        postsCount: '4.5m',
    },
    {
        id: '5',
        userProfilePic: require('../../assets/images/users/user23.png'),
        hastag: '#drink',
        postsCount: '4.5m',
    },
    {
        id: '6',
        userProfilePic: require('../../assets/images/users/user24.png'),
        hastag: '#traveldairies',
        postsCount: '4.5m',
    },
    {
        id: '7',
        userProfilePic: require('../../assets/images/users/user25.png'),
        hastag: '#cocoresidencemaldives',
        postsCount: '5.5m',
    },
    {
        id: '8',
        userProfilePic: require('../../assets/images/users/user26.png'),
        hastag: '#travelworld',
        postsCount: '1.5m',
    },
    {
        id: '9',
        userProfilePic: require('../../assets/images/users/user19.png'),
        hastag: '#surfing',
        postsCount: '1.5m',
    },
    {
        id: '10',
        userProfilePic: require('../../assets/images/users/user20.png'),
        hastag: '#landscape',
        postsCount: '57,793,278',
    },
    {
        id: '11',
        userProfilePic: require('../../assets/images/users/user21.png'),
        hastag: '#landscapephotography',
        postsCount: '57,793,278',
    },
];