export const notifications = [
    {
        key: "1",
        itemType: 'User',
        type: "following",
        userProfilePic: require("../../assets/images/users/user12.png"),
        userName: "Stefan Vasilescu",
        notificationTime: "3 minutes ago",
    },
    {
        key: "2",
        itemType: 'Sportiv',
        type: "likeMorePhotos",
        userProfilePic: require("../../assets/images/users/user2.png"),
        userName: "Ana Maria Dumitrescu",
        likedPohotos: [
            {
                id: "1",
                photo: require("../../assets/images/posts/post6.png"),
            },
            {
                id: "2",
                photo: require("../../assets/images/posts/post7.png"),
            },
            {
                id: "3",
                photo: require("../../assets/images/posts/post8.png"),
            },
        ],
        notificationTime: "5 minutes ago",
    },
    {
        key: "3",
        itemType: 'User',
        type: "likeOnePhoto",
        userProfilePic: require("../../assets/images/users/user30.png"),
        userName: "Alexandru Ionescu",
        likedPhoto: require("../../assets/images/gallery/gallery1.png"),
        notificationTime: "15 minutes ago",
    },
    {
        key: "4",
        itemType: 'Club',
        id: "1",
        userProfilePic: require("../../assets/images/users/user37.png"),
        userName: "Event 0",
        userDetail: "Predeal, Brasov",
        aboutPost:
            "Nu pierdeti ocazia de a fi martori la viitorii campioni de baschet in acțiune, la turneul pentru juniori din Predeal!",
        postLikes: "10k",
        postComments: "100",
        postShares: "35",
        postImage: require("../../assets/images/contests/basketball.jpg"),
        postLike: true,
        type: "post",
    },
    {
        key: "5",
        type: "following",
        itemType: 'User',
        userProfilePic: require("../../assets/images/users/user30.png"),
        userName: "Andrei Popescu",
        notificationTime: "20 minutes ago",
    },
    {
        key: "6",
        type: "mention",
        itemType: 'Business',
        userProfilePic: require("../../assets/images/users/user3.png"),
        mentionPhoto: require("../../assets/images/gallery/gallery1.png"),
        userName: "@mariaVasilescu",
        mantionUserName: "@mariaVasilescu",
        comment: "foarte frumos...",
        notificationTime: "35 minutes ago",
    },
    {
        key: "7",
        type: "following",
        itemType: 'User',
        userProfilePic: require("../../assets/images/users/user29.png"),
        userName: "Ionut Petrescu",
        notificationTime: "40 minutes ago",
    },
    {
        key: "8",
        itemType: 'Business',
        type: "likeMorePhotos",
        userProfilePic: require("../../assets/images/users/user4.png"),
        userName: "Andrei Popescu",
        likedPohotos: [
            {
                id: "1",
                photo: require("../../assets/images/publicPosts/post23.png"),
            },
            {
                id: "2",
                photo: require("../../assets/images/publicPosts/post24.png"),
            },
            {
                id: "3",
                photo: require("../../assets/images/publicPosts/post20.png"),
            },
            {
                id: "4",
                photo: require("../../assets/images/publicPosts/post11.png"),
            },
        ],
        notificationTime: "50 minutes ago",
    },
    {
        key: "9",
        itemType: 'Club',
        type: "likeOnePhoto",
        userProfilePic: require("../../assets/images/users/user41.png"),
        userName: "Alexandru Ionescu",
        likedPhoto: require("../../assets/images/gallery/gallery5.png"),
        notificationTime: "15 minutes ago",
    },
    {
        key: "10",
        itemType: 'Business',
        type: "mention",
        userProfilePic: require("../../assets/images/users/user3.png"),
        mentionPhoto: require("../../assets/images/gallery/gallery1.png"),
        userName: "alexionescu.",
        mantionUserName: "@alexionescu",
        comment: "foarte frumos...",
        notificationTime: "acum 2 zile",
    },
    {
        key: "11",
        itemType: 'Club',
        type: "likeByMore",
        userProfilePics: [
            {
                id: "1",
                userProfilePic: require("../../assets/images/users/user41.png"),
            },
            {
                id: "2",
                userProfilePic: require("../../assets/images/users/user42.png"),
            },
        ],
        userProfileNames: ["George Popa", "Alexandru Ionescu", "", "", "", ""],
        likedPhoto: require("../../assets/images/posts/post10.png"),
        notificationTime: "acum 2 zile",
    },
    {
        key: "12",
        itemType: 'Business',
        type: "seeOldPost",
        postTime: "1 year ago",
        seeTime: "azi",
        post: require("../../assets/images/gallery/gallery5.png"),
        notificationTime: "acum 3 zile",
    },
    {
        key: "13",
        itemType: 'Business',
        type: "likeByMore",
        userProfilePics: [
            {
                id: "1",
                userProfilePic: require("../../assets/images/users/user41.png"),
            },
            {
                id: "2",
                userProfilePic: require("../../assets/images/users/user42.png"),
            },
        ],
        userProfileNames: ["Ana Maria Dumitrescu", "George Popa", "", "", "", ""],
        likedPhoto: require("../../assets/images/posts/post10.png"),
        notificationTime: "acum 2 zile",
    },
    {
        key: "14",
        itemType: 'Sportiv',
        type: "mention",
        userProfilePic: require("../../assets/images/users/user3.png"),
        mentionPhoto: require("../../assets/images/gallery/gallery1.png"),
        userName: "alexionescu.",
        mantionUserName: "@alexionescu",
        comment: "foarte frumos...",
        notificationTime: "acum 3 zile",
    },
    {
        key: "15",
        type: "likeMorePhotos",
        itemType: 'Sportiv',
        userProfilePic: require("../../assets/images/users/user4.png"),
        userName: "Ana Maria Dumitrescu",
        likedPohotos: [
            {
                id: "1",
                photo: require("../../assets/images/publicPosts/post23.png"),
            },
            {
                id: "2",
                photo: require("../../assets/images/publicPosts/post24.png"),
            },
            {
                id: "3",
                photo: require("../../assets/images/publicPosts/post20.png"),
            },
            {
                id: "4",
                photo: require("../../assets/images/publicPosts/post11.png"),
            },
        ],
        notificationTime: "50 minutes ago",
    },
];

export const azisPostsList = [
    {
        id: "1",
        itemType: 'Business',
        userProfilePic: require("../../assets/images/users/user37.png"),
        userName: "Event 0",
        userDetail: "Predeal, Brasov",
        aboutPost:
            "Nu pierdeti ocazia de a fi martori la viitorii campioni de baschet in acțiune, la turneul pentru juniori din Predeal!",
        postLikes: "10k",
        postComments: "100",
        postShares: "35",
        postImage: require("../../assets/images/contests/basketball.jpg"),
        postLike: true,
    },
    {
        id: "2",
        itemType: 'Business',
        userProfilePic: require("../../assets/images/users/user26.png"),
        userName: "Event 1",
        userDetail: "Predeal, Brasov",
        aboutPost:
            "Vino sa vezi talentele viitorului in acțiune la turneul de fotbal pentru juniori din Predeal!",
        postLikes: "10k",
        postComments: "100",
        postShares: "35",
        postImage: require("../../assets/images/contests/football.jpg"),
        postLike: false,
    },
];