const usersList = [
    {
        id: '1',
        userProfilePic: require('../../assets/images/users/user12.png'),
        userProfileName: 'jiyashah_',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:50 am',
        isActive: true,
    },
    {
        id: '2',
        userProfilePic: require('../../assets/images/users/user44.png'),
        userProfileName: 'royyy.___',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:30 am',
        isActive: true,
    },
    {
        id: '3',
        userProfilePic: require('../../assets/images/users/user29.png'),
        userProfileName: 'monaliali.',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:28 am',
        isActive: false,
    },
    {
        id: '4',
        userProfilePic: require('../../assets/images/users/user13.png'),
        userProfileName: 'dhirajshah__',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:20 am',
        isActive: false,
    },
    {
        id: '5',
        userProfilePic: require('../../assets/images/users/user31.png'),
        userProfileName: 'vaishanavi__',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:15 am',
        isActive: true,
    },
    {
        id: '6',
        userProfilePic: require('../../assets/images/users/user14.png'),
        userProfileName: 'ishankhatri.',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:00 am',
        isActive: true,
    },
    {
        id: '7',
        userProfilePic: require('../../assets/images/users/user32.png'),
        userProfileName: 'diya.___',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '9:45 am',
        isActive: true,
    },
    {
        id: '8',
        userProfilePic: require('../../assets/images/users/user45.png'),
        userProfileName: 'ishaofficial.',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '9:00 am',
        isActive: true,
    },
    {
        id: '9',
        userProfilePic: require('../../assets/images/users/user10.png'),
        userProfileName: 'jiyashah_',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:50 am',
        isActive: true,
    },
    {
        id: '10',
        userProfilePic: require('../../assets/images/users/user3.png'),
        userProfileName: 'royyy.___',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:30 am',
        isActive: true,
    },
    {
        id: '11',
        userProfilePic: require('../../assets/images/users/user27.png'),
        userProfileName: 'monaliali.',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:28 am',
        isActive: false,
    },
    {
        id: '12',
        userProfilePic: require('../../assets/images/users/user5.png'),
        userProfileName: 'dhirajshah__',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:20 am',
        isActive: false,
    },
    {
        id: '13',
        userProfilePic: require('../../assets/images/users/user6.png'),
        userProfileName: 'vaishanavi__',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:15 am',
        isActive: true,
    },
    {
        id: '14',
        userProfilePic: require('../../assets/images/users/user8.png'),
        userProfileName: 'ishankhatri.',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '10:00 am',
        isActive: true,
    },
    {
        id: '15',
        userProfilePic: require('../../assets/images/users/user2.png'),
        userProfileName: 'diya.___',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '9:45 am',
        isActive: true,
    },
    {
        id: '16',
        userProfilePic: require('../../assets/images/users/user1.png'),
        userProfileName: 'ishaofficial.',
        lastMsg: 'Lorem Ipsum is simply dummy text',
        lastMsgTime: '9:00 am',
        isActive: true,
    },
];

export default usersList;